stages:
  - test
#  - deploy_prod


# Variables
variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: homestead
  MYSQL_PASSWORD: secret
  MYSQL_DATABASE: homestead
  DB_HOST: mysql

# Speed up builds
cache:
  key: $CI_BUILD_REF_NAME # changed to $CI_COMMIT_REF_NAME in Gitlab 9.x
  paths:
    - vendor
    - node_modules
    - public
    - .yarn


test:
  stage: test
  services:
    - mysql:5.7
  image: edbizarro/gitlab-ci-pipeline-php:8.0-alpine
  script:
    - yarn config set cache-folder .yarn
    - yarn install --pure-lockfile
    - yarn prod
    - composer install --prefer-dist --no-ansi --no-interaction --no-progress
    - cp .env.example .env
    - php artisan key:generate
    - php artisan migrate:refresh --seed
    - ./vendor/phpunit/phpunit/phpunit -v --coverage-text --colors=never --stderr
  artifacts:
    paths:
      - ./storage/logs # for debugging
    expire_in: 7 days
    when: always

#deploy_develop:
#   stage: deploy
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo -e "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
#     - chmod 700 ~/.ssh/id_rsa
##     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#   script:
##     - ssh youlook@$DEV_SERVER "cd ~/www && git pull origin develop && ~/bin/composer install"
#     - ssh root@82.202.246.239
###   environment:
###     name: develop
###     url: https://develop.zah.me/
##   only:
##     - develop


#deploy_master:
#   stage: deploy__prod
#
#   before_script:
#     - mkdir -p ~/.ssh
#     - echo -e "$DEPLOY_KEY" > ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
#
#   script:
#     - ssh root@82.202.246.239 "
#          cd /srv/yl-web/latest &&
#          git checkout . &&
#          git checkout develop &&
#          git pull &&
#
#
#
#          php artisan migrate --force &&
#          npm install &&
#          npm run production"
#
##   environment:
##     name: develop
##     url: https://develop.zah.me/
#   only:
#     - develop
